#!/bin/bash

audio_fifo_path=/tmp/vdiguest-audio
period=1
if [ $# -eq 1 ]; then
	period=$1
fi

prev_nr_mem=0
while true; do
	nr_mem=`pacmd stat | grep "POOL:" | awk '{print $7}' | cut -d/ -f2`
	if [ $nr_mem -gt $prev_nr_mem ]; then
		echo > $audio_fifo_path
	fi
	prev_nr_mem=$nr_mem

	sleep $period
done
